Repository proteneer/timemachine, pull requests merged in 2022-02, with the labels that each got.

#589 Upgrade jax and jaxlib, install with conda
  README.md
  environment.yml
  fe/loss.py
  requirements.txt
  slow_tests/test_mtm.py
  tests/test_bonded.py
Labels: spring cleaning

#592 Move `scripts/` to `attic/scripts/`
  attic/readme.md
  attic/scripts/bootstrap_am1.py
Labels: spring cleaning, the-great-namespace-migration

#593 Move `md/` to `timemachine/md/`
  attic/training/hydration_fe.py
  docking/dock_and_equilibrate.py
  docking/relative_docking.py
  docking/rigorous_work.py
  examples/ahfe.py
  examples/estimator_variance.py
  examples/hif2a/fit_to_multiple_rbfes.py
  examples/npt_equilibration.py
  examples/rbfe_single.py
  examples/rhfe_dual.py
  examples/rhfe_single.py
  examples/validate_relative_binding.py
  examples/validate_relative_hydration.py
  slow_tests/test_barostat.py
  slow_tests/test_barostat_water_density.py
  slow_tests/test_benchmark.py
  slow_tests/test_determinism.py
  slow_tests/test_free_energy.py
  slow_tests/test_minimizer.py
  slow_tests/test_mtm.py
  slow_tests/test_mtm_condensed.py
  slow_tests/test_rbfe.py
  slow_tests/test_vacuum_importance_sampling.py
  tests/dual_topology.py
  tests/test_centroid_rescaler.py
  tests/test_ensembles.py
  tests/test_estimator.py
  tests/test_jax_nonbonded.py
  tests/test_jit.py
  tests/test_nblist.py
  tests/test_nonbonded.py
  tests/test_pdb_writer.py
  tests/test_rabfe.py
  timemachine/fe/estimator.py
  timemachine/fe/estimator_abfe.py
  timemachine/fe/model.py
  timemachine/fe/model_rabfe.py
  timemachine/md/__init__.py
  timemachine/md/barostat/__init__.py
  timemachine/md/barostat/moves.py
  timemachine/md/barostat/utils.py
  timemachine/md/builders.py
  timemachine/md/enhanced.py
  timemachine/md/ensembles.py
  timemachine/md/fire.py
  timemachine/md/minimizer.py
  timemachine/md/moves.py
  timemachine/md/states.py
  timemachine/md/thermostat/__init__.py
  timemachine/md/thermostat/moves.py
  timemachine/md/thermostat/utils.py
  timemachine/md/utils.py
Labels: spring cleaning, the-great-namespace-migration

#597 Add setuptools config, set up versioneer
  .gitattributes
  .gitignore
  .pre-commit-config.yaml
  MANIFEST.in
  Makefile
  README.md
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  timemachine/__init__.py
  timemachine/_version.py
  timemachine/cpp/CMakeLists.txt
  versioneer.py
Labels: spring cleaning

#610 Speed up slow tests in test_md.py
  slow_tests/test_reference_langevin_integrator.py
  tests/test_md.py
Labels: spring cleaning

#615 Move `testsystems/` and `datasets/` to timemachine namespace
  attic/training/hydration_cfg.ini
  examples/hif2a/hif2a_config.yaml
  examples/npt_equilibration.py
  examples/potential_energy.py
  examples/rbfe_single.py
  slow_tests/test_barostat.py
  slow_tests/test_barostat_water_density.py
  slow_tests/test_benchmark.py
  slow_tests/test_determinism.py
  slow_tests/test_docking.py
  slow_tests/test_free_energy.py
  slow_tests/test_rbfe.py
  slow_tests/test_reference_langevin_integrator.py
  tests/test_atom_mapping.py
  tests/test_jit.py
  tests/test_nblist.py
  tests/test_pdb_writer.py
  tests/test_rabfe.py
  tests/test_rmsd_align.py
  tests/test_training.py
  timemachine/datasets/fep-benchmark/hif2a/5tbm_prepared.pdb
  timemachine/datasets/fep-benchmark/hif2a/README.md
  timemachine/datasets/fep-benchmark/hif2a/ligands.sdf
  timemachine/datasets/fep-benchmark/hif2a/results_20ns.csv
  timemachine/datasets/fep-benchmark/hif2a/results_5ns.csv
  timemachine/datasets/fep-benchmark/hif2a/results_edges_20ns.csv
  timemachine/datasets/fep-benchmark/hif2a/results_edges_5ns.csv
  timemachine/datasets/freesolv/freesolv.sdf
  timemachine/datasets/readme.md
  timemachine/testsystems/relative.py
Labels: spring cleaning, the-great-namespace-migration

#630 Fix np.testing.assert_almost_equal usage
  tests/common.py
  tests/test_bonded.py
  tests/test_nonbonded.py
  tests/test_parameter_interpolation.py
Labels: bug
